services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: njstudios
      POSTGRES_PASSWORD: Spencer#00
      POSTGRES_DB: voice_notes
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "npm install
             && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
